Section A: Data Structures & Control Structures
1. List Operations

In [1]:
nums = [10, 20, 30, 40, 50]

nums.append(60)
print("append:", nums)

nums.extend([70, 80])
print("extend:", nums)

nums.insert(2, 25)
print("insert:", nums)

nums.remove(25)
print("remove:", nums)

nums.pop()
print("pop:", nums)

print("index of 40:", nums.index(40))

print("count of 20:", nums.count(20))

nums.sort()
print("sort:", nums)

nums.reverse()
print("reverse:", nums)

nums.clear()
print("clear:", nums)

append: [10, 20, 30, 40, 50, 60]
extend: [10, 20, 30, 40, 50, 60, 70, 80]
insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
remove: [10, 20, 30, 40, 50, 60, 70, 80]
pop: [10, 20, 30, 40, 50, 60, 70]
index of 40: 3
count of 20: 1
sort: [10, 20, 30, 40, 50, 60, 70]
reverse: [70, 60, 50, 40, 30, 20, 10]
clear: []


2. Tuple

In [6]:
students = ("Ravi", "Priya", "Kiran")

students_list = list(students)
students_list[1] = "Anjali"

students = tuple(students_list)

print(students)

('Ravi', 'Anjali', 'Kiran')


3. Set with Duplicates

In [7]:
numbers = {1, 2, 3, 4, 4, 5, 2, 1}

print(numbers)

{1, 2, 3, 4, 5}


4. Dictionary

In [8]:
person = {
    "name": "Raj",
    "age": 20,
    "city": "Nellore"
}

person["age"] = 21
person["email"] = "raj@gmail.com"

print(person)

{'name': 'Raj', 'age': 21, 'city': 'Nellore', 'email': 'raj@gmail.com'}


5. Voting Eligibility

In [9]:
age = 19

if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Eligible to vote


6. Grade Calculator

In [10]:
marks = 82

if marks >= 90:
    print("A")
elif marks >= 75:
    print("B")
elif marks >= 50:
    print("C")
else:
    print("Fail")

B


7. Positive, Even, Zero or Negative

In [12]:
num = 12

if num > 0:
    print("Positive Number")

    if num % 2 == 0:
        print("Even Number")
    else:
        print("Odd Number")

elif num == 0:
    print("Zero")

else:
    print("Negative Number")

Positive Number
Even Number


Section B: NumPy
8. Scalar, 1D Array, 2D Array

In [13]:
import numpy as np

scalar = np.array(5)
print("Scalar:")
print(scalar)

arr1 = np.array([1, 2, 3, 4, 5])
print("\n1D Array:")
print(arr1)

arr2 = np.array([[10, 20, 30],
                 [40, 50, 60]])
print("\n2D Array:")
print(arr2)

Scalar:
5

1D Array:
[1 2 3 4 5]

2D Array:
[[10 20 30]
 [40 50 60]]


9. Random 4×4 Array

In [14]:
import numpy as np

arr = np.random.randint(0, 101, size=(4, 4))

print(arr)

[[21 56  0 23]
 [39 84 32 50]
 [42 45 84  9]
 [66 34 83 86]]


10. NumPy Array to Pandas DataFrame

In [15]:
import numpy as np
import pandas as pd

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

df = pd.DataFrame(array, columns=["A", "B", "C"])

print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


Section C: Exploring Pandas
11. DataFrame Operations

In [16]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Raj", "Anu", "Kiran", "Priya", "Ravi",
             "Sita", "Arun", "Divya", "Raj", "Kiran"],

    "Age": [20, 22, 21, 23, 24,
            25, 22, 21, 20, 21],

    "City": ["Nellore", "Chennai", "Hyderabad", "Bangalore",
             "Mumbai", "Delhi", "Pune", "Kolkata",
             "Nellore", "Hyderabad"],

    "Salary": [25000, 30000, np.nan, 35000,
               40000, 28000, np.nan, 32000,
               25000, np.nan]
}

df = pd.DataFrame(data)

print("DataFrame:")
print(df)

print("\nInfo:")
print(df.info())

print("\nDescribe:")
print(df.describe())

print("\nName and City Columns:")
print(df[["Name", "City"]])

df = df.drop("City", axis=1)

mean_salary = df["Salary"].mean()
df["Salary"] = df["Salary"].fillna(mean_salary)

df = df.drop_duplicates()

print("\nFinal DataFrame:")
print(df)

DataFrame:
    Name  Age       City   Salary
0    Raj   20    Nellore  25000.0
1    Anu   22    Chennai  30000.0
2  Kiran   21  Hyderabad      NaN
3  Priya   23  Bangalore  35000.0
4   Ravi   24     Mumbai  40000.0
5   Sita   25      Delhi  28000.0
6   Arun   22       Pune      NaN
7  Divya   21    Kolkata  32000.0
8    Raj   20    Nellore  25000.0
9  Kiran   21  Hyderabad      NaN

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  7 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

Describe:
            Age        Salary
count  10.00000      7.000000
mean   21.90000  30714.285714
std     1.66333   5468.524655
min    20.00000  25000.000000
25%    21.00000  26500.000000
50%    21.50000  30000